name: linux-otlp-metrics

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run prometheus
        run: |
          docker run -p 9090:9090 -v ./tests/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus --web.enable-otlp-receiver --config.file=/etc/prometheus/prometheus.yml
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - name: Run tests
        run: |
          cargo fmt --check
          cargo clippy
          cargo test -- --test-threads=1
